apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: chat
  ports:
    - port: 4000
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: app
          image: chat-api2.5
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgresSuperUserPsw@postgres:5432/postgres?schema=public
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              value: 'test'
            - name: HOST
              value: '0.0.0.0'
            - name: PORT
              value: '4000'
            - name: CORS_ORIGIN
              value: 'http://localhost:3000'
            - name: AUTH0_AUDIENCE
              value: https://dev--2cpvhzk.us.auth0.com/api/v2/
            - name: AUTH0_JWKS_URI
              value: https://dev--2cpvhzk.us.auth0.com/.well-known/jwks.json
            - name: AUTH0_SIGNING_ALG
              value: RS256
            - name: AUTH0_ISSUER_BASE_URL
              value: https://dev--2cpvhzk.us.auth0.com/
            - name: AUTH0_HOOK_SECRET
              value: '$#@d23fWEFR23f3f3f32f'
            - name: HASH_SALT
              value: 'test'
            - name: HASH_MIN_LENGTH
              value: '11'
            - name: APOLLO_KEY
              value: service:graphchat:F9dxVKPpvau0iE5ncZuQoA
            - name: APOLLO_GRAPH_REF
              value: graphchat@current
            - name: APOLLO_SCHEMA_REPORTING
              value: 'true'

